language: nix
matrix:
  include:
    - name: 18.09 macOS
      env: CHANNEL=nixpkgs-18.09-darwin
      os: osx
    - name: 18.09 nixOS
      env: CHANNEL=nixos-18.09

script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cat .travis.nix.conf | sudo tee -a  /etc/nix/nix.conf; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pkill nix-daemon && sudo nix-daemon & fi
- nix-env -iA cachix -f https://github.com/NixOS/nixpkgs/tarball/889c72032f8595fcd7542c6032c208f6b8033db6
- cachix use nix-tools-2
- # sudo cachix use nix-tools
- if [[ $TRAVIS_SECURE_ENV_VARS ]]; then
  nix-build
  -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/${CHANNEL}.tar.gz
  -A nix-tools-all-execs
  --cores 0
  | cachix push nix-tools-2;
  else
  nix-build
  -I nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/${CHANNEL}.tar.gz
  -A nix-tools-all-execs
  --cores 0;
  fi

env:
  global:
#    secure: wpJCKjz4HAN0UBN8261g8Wp1UpSW5KjggCSGWBT72gvoB4F+uqqzHeVr4sKpaDcDVEUgirmYvcGi0UerkBKygvQMwTNI7rXvIk4wHG16T1M/1G/Ck7w0ca5bQNtt+lEStTmP2RS9VOvu9AOrqUBP4NDvTy0K96dQg7yGAVnVydsmn6KMJ5sSyLp8jKYYVhYrx/1HPEgFWR69W1LMsXdP6bI3PGTkBaXHaSYlfubMvFxSU5EkYuI0O6Y35BrT0guVJRu+uhE25lFVum00gSOclh8ZkurtYfioamdnkDr0AwiWj5MZ6m3hIOml6OS+yJrmUncet+G7m03xIz/sQBCrZgsFJIQDAktH0lOiqVxHipy9ufdyMoBblN6Zq90YlvVcflhtibo25HoXTKyY2fJaN9DOD5HPTDsKQmYYs/FjDLUqntlGuF3vjnFA4ZcfqpQTBYyHgdbCnvTZTbxYYhbaaIyJ7nnEGuQckMqqfM2Wu7enDhbH0xRXufhsC4imEF2sJFkXWR4Q5V4G1I+dj/FW1vgyYMJCoC9IHRPjUcdLSmiaDTdW/xjTqR3P2XXxdqD9SLxMaYo9KeqmhF7zMUn+sxHyhm76ci2SRjK9nOFlmggw/VtSag292WJaWdUJROo3XJbOA+e5YYR6uYRpB5UqVFaZZBlgxHcaVsCl217cbj0=
    secure: jmcbW43BK4dKx9cGLD4k1MA1teW2M9a8GcSqYyv4VIEM2bdsJxAjQzlrDDDVi32AorvpD3Gkx/rTHlBejSa48lHpLQ7UmGJgl/0yMv8dOvXHZR+ZA4XyMw9ZSwLkLbRKD3a+l9Ryf0yNgDXByypP8SiUVeuZ1T1AB4V0cB9GF7N19VT07xNjD9ArFGCiizuPpzq0h9kneAzDRLOzyXYKvTm6THUnWTLAQRGMAPBFYacyBZFIb23t77tD2VQX/FBUuINyg433ZV6IbU6HEzXILbF+Ar8zd6PpDZlLMrQo+8QlxPItBy2UoYfpPBe+xyjlAUu2jvtc4ySUu1wYLkWXk2OQPS12z+t5E441XH3uqjD5QpHShQY5Qh+zwIqZQmsMsu0jiUUJ412aoz5Cx1/C+hNmjfD9xFM3Jf9hnmZ3czNgXO7Sian4ZFBATaSgEXGeEaLATEZsjnvj09+pB8fWr5+otIBDzfux1MNBJ+J9+oqay0zF2Jeey7kaDJ8KxVeWz9QAnTDtPT1qsfsRHitFWzQsIofRGVxwAnHphUVtxz9ve8IxqZxTojhMTFo4bpGMAoQX0tiIUHEUWscpUt3hBBgTjLFEJcROwMI4k1V3ZBWSDhml8V46XN6vE974tzKFKFeQSnVscniG5K+j4260Sgn2P+/VvvggMi6/FEgifVY=
